### ISSUE TITLE
Version 0.6

### ISSUE THREAD

**Issue by Steelstone3** [Steelstone3/Critter-Cove-Zoo-Manager#13]
# Goal

- UI Additions That Use Existing Spawn Systems
- Fixes to spawning system

# Task List

- [x] **User interface feedback**
- [x] Sprite sheets into individual sprite assets
- [x] Tree main menu
- [x] Tree sub menu
- [x] Tree spawning (like animal)
- [x] Rock main menu
- [x] Rock sub menu
- [x] Rock spawning (like animal)
- [x] Complete animal sub menu
- [x] Synchronise current spawning system to mouse pointer
  - [x] Mouse doesn't indicate where sprite will spawn in certain conditions
  - [x] Camera movement
  - [x] Camera zoom
