### ISSUE TITLE
Version 0.8

### ISSUE THREAD

**Issue by Steelstone3** [Steelstone3/Critter-Cove-Zoo-Manager#15]
# Goal

- Zoo Management Systems
- Crowds
- AI Pathing

# Tasks

- [ ] Cost associated with each spawn-able item (animals, fences, terrain, trees, rocks, shelter, paths)
- [ ] Create a basic system that slowly earns money back for each new visitor + number of animals (clamp to a max value)
- [ ] Creating individual animate-able people sprite sheets from the main people sprite sheet
- [ ] Spawning people on paths (limited to 1000)
- [ ] People AI pathing to remain on or move to nearest path (navigating around fences)
- [ ] Collision system with fences for people and animals
- [ ] Animals roam within fenced area unless escaped (where they will use the original pathing)
