### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by Steelstone3** [Steelstone3/Critter-Cove-Zoo-Manager#17]
# Goal

- Drag and drop animal system (where the AI turns off whilst being dragged)
- Escape system for unhappy, aggressive animals
- Animal behaviour

# Tasks

- [ ] Animal behaviours based on Herbivore, Omnivore or Carnivore
  - [ ] Herbivore non violent, unlikely to escape when unhappy but will mess up enclosure randomly changing the terrain
  - [ ] Omnivore non violent to humans unless hungry or angry and escaped
  - [ ] Carnivore generally aggressive to humans
- [ ] Animal suitability to enclosure
  - [ ] If unhappy, hungry and angry will attempt escape
  - [ ] Fence repair needed
  - [ ] Drag and drop required to recover animal
  - [ ] Suitability needed for enclosure
  - [ ] User feedback for what is and isn't good
- [ ] Humans attacked by animals system
  - [ ] When animals have escaped from being unhappy
  - [ ] Humans will be killed in animal attacks
  - [ ] Humans will attempt to flee animal
